# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 08:46
from __future__ import unicode_literals

import cloneable_model.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='modules.Category')),
            ],
            options={
                'abstract': False,
            },
            bases=(cloneable_model.models.CloneableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='media')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.ConferenceAttendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPresenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.Module')),
            ],
            bases=('modules.module',),
        ),
        migrations.CreateModel(
            name='PresentersModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.Module')),
            ],
            bases=('modules.module',),
        ),
        migrations.CreateModel(
            name='ScheduleModule',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modules.Module')),
            ],
            bases=('modules.module',),
        ),
        migrations.AddField(
            model_name='module',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
        ),
        migrations.AddField(
            model_name='eventpresenter',
            name='presenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Presenter'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', through='modules.EventAttendee', to='conferences.ConferenceAttendee'),
        ),
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(blank=True, through='modules.EventDocument', to='modules.Document'),
        ),
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='modules.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(blank=True, to='conferences.ConferenceAttendee'),
        ),
        migrations.AddField(
            model_name='event',
            name='presenters',
            field=models.ManyToManyField(blank=True, through='modules.EventPresenter', to='modules.Presenter'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.PresentersModule'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='modules.ScheduleModule'),
        ),
        migrations.AddField(
            model_name='document',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.DocumentsModule'),
        ),
        migrations.AddField(
            model_name='category',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.DocumentsModule'),
        ),
    ]
