# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uroboros',
            old_name='uroboros',
            new_name='parent',
        ),
    ]
